// Re-export axum Router so build-generated routes.rs can reference it.
use axum::extract::{Request, State};
use axum::http::{HeaderName, HeaderValue, StatusCode};
use axum::middleware::Next;
use axum::response::Response;
pub use axum::Router;

const MW_ORDER_HEADER: &str = "x-krab-route-mw-order";
const MW_SHORT_CIRCUIT_HEADER: &str = "x-krab-route-mw-short-circuit";

fn append_middleware_order(req: &mut Request, middleware_name: &str) {
    let existing = req
        .headers()
        .get(MW_ORDER_HEADER)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("");

    let updated = if existing.is_empty() {
        middleware_name.to_string()
    } else {
        format!("{existing},{middleware_name}")
    };

    if let Ok(value) = HeaderValue::from_str(&updated) {
        req.headers_mut()
            .insert(HeaderName::from_static(MW_ORDER_HEADER), value);
    }
}

fn propagate_middleware_order(req: &Request, response: &mut Response) {
    if response.headers().contains_key(MW_ORDER_HEADER) {
        return;
    }
    if let Some(value) = req.headers().get(MW_ORDER_HEADER).cloned() {
        response
            .headers_mut()
            .insert(HeaderName::from_static(MW_ORDER_HEADER), value);
    }
}

pub async fn middleware_probe_first<S>(
    State(_state): State<S>,
    mut req: Request,
    next: Next,
) -> Response
where
    S: Clone + Send + Sync + 'static,
{
    append_middleware_order(&mut req, "middleware_probe_first");
    let mut response = next.run(req).await;
    // Keep the response order header stable even if inner layers did not set it.
    if !response.headers().contains_key(MW_ORDER_HEADER) {
        response.headers_mut().insert(
            HeaderName::from_static(MW_ORDER_HEADER),
            HeaderValue::from_static("middleware_probe_first"),
        );
    }
    response
}

pub async fn middleware_probe_second<S>(
    State(_state): State<S>,
    mut req: Request,
    next: Next,
) -> Response
where
    S: Clone + Send + Sync + 'static,
{
    append_middleware_order(&mut req, "middleware_probe_second");

    let should_short_circuit = req
        .headers()
        .get(MW_SHORT_CIRCUIT_HEADER)
        .and_then(|v| v.to_str().ok())
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false);

    if should_short_circuit {
        let mut response = Response::new(axum::body::Body::empty());
        *response.status_mut() = StatusCode::FORBIDDEN;
        propagate_middleware_order(&req, &mut response);
        return response;
    }

    let mut response = next.run(req).await;
    response.headers_mut().insert(
        HeaderName::from_static(MW_ORDER_HEADER),
        HeaderValue::from_static("middleware_probe_first,middleware_probe_second"),
    );
    response
}

// File-System Routes (generated by build.rs, Axum-compatible)
include!(concat!(env!("OUT_DIR"), "/routes.rs"));
// Build-time SSG metadata (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/ssg.rs"));

#[cfg(test)]
mod tests {
    use crate::{
        discovered_static_routes, enumerate_dynamic_route_params, register_routes,
        ssg_manifest_json, Router,
    };
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use krab_core::Render;
    use krab_macros::view;
    use tower::ServiceExt;

    #[test]
    fn ssr_snapshot_home_fragment() {
        let rendered = view! {
            <div id="snapshot-root">
                <h1>"Krab Framework"</h1>
                <p>"SSR snapshot baseline"</p>
            </div>
        }
        .render();

        let expected =
            "<div id=\"snapshot-root\"><h1>Krab Framework</h1><p>SSR snapshot baseline</p></div>";
        assert_eq!(rendered, expected);
    }

    #[test]
    fn ssg_discovery_contract_is_generated() {
        let routes = discovered_static_routes();
        assert!(routes.contains(&"/"));
        assert!(routes.contains(&"/about"));

        let params = enumerate_dynamic_route_params();
        let blog = params
            .get("/blog/{slug}")
            .expect("blog dynamic params should exist");
        assert!(!blog.is_empty());

        let manifest = ssg_manifest_json();
        assert!(manifest.contains("discovered_routes"));
        assert!(manifest.contains("asset_manifest"));
    }

    #[tokio::test]
    async fn route_level_middlewares_execute_in_declared_order() {
        let app = register_routes(Router::new(), ());
        let request = Request::builder()
            .method("GET")
            .uri("/api/middleware_probe")
            .body(Body::empty())
            .unwrap();

        let response = app.oneshot(request).await.unwrap();
        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get("x-krab-route-mw-order")
                .and_then(|v| v.to_str().ok()),
            Some("middleware_probe_first,middleware_probe_second")
        );
    }

    #[tokio::test]
    async fn route_level_middlewares_can_short_circuit() {
        let app = register_routes(Router::new(), ());
        let request = Request::builder()
            .method("GET")
            .uri("/api/middleware_probe")
            .header("x-krab-route-mw-short-circuit", "1")
            .body(Body::empty())
            .unwrap();

        let response = app.oneshot(request).await.unwrap();
        assert_eq!(response.status(), StatusCode::FORBIDDEN);
        assert_eq!(
            response
                .headers()
                .get("x-krab-route-mw-order")
                .and_then(|v| v.to_str().ok()),
            Some("middleware_probe_first,middleware_probe_second")
        );
    }
}
